AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  GetMyTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: src/mytext.get
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /mytext
            Method: get
  PostMyTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: src/mytext.post
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /mytext
            Method: post
  TextsTable:
    Type: AWS::DynamoDB::SimpleTable
    Properties:
      TableName: sharemytext.Texts
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5